#!/bin/bash
pip3 install pipreqs
pipreqs
pip3 install -r requirements.txt 
rm requirements.txt
curl -sSL https://install.python-poetry.org | python3 -
pip3 install poetry
poetry install
pip3 install mypy